### ISSUE TITLE
Dual Strong Copyleft Licensing

### ISSUE THREAD

**Issue by calumapplepie** [ZipCPU/zipversa#2]
Hello, I'm working on a somewhat similar project to this (SilliconJson, name pending), but have decided on a different license than the GPL; the CERN-OHL-S, a strong-copyleft license specialized for hardware.  While some future version of it might create an exception to allow for OHL-S cores to use and be used by GPL cores, there isn't any such exception now, meaning that projects must be dual-licensed by the owner (eg, you say "this is available under the GPL or the OHL).  Since you appear to be working on open hardware, I figured you'd like to know, both about my project and about the OHL-S.

I'm not currently planning or hoping to integrate any parts of this design into SilliconJson, but it would be cool to know if I had the ability.  The OHL-S imposes stricter requirements on any eventual use in hardware than the GPL, so dual licensing wouldn't harm your business model.

Thanks,
Calum

**Comment by ZipCPU** [comment]
Do you have a link for the CERN license?  I've had been watching them, but lost touch with their project some years back -- before their license was ready for prime time.  If they're ready for use, I'll look into it.

**Comment by calumapplepie** [comment]
https://ohwr.org/project/cernohl/wikis/Documents/CERN-OHL-version-2

I'm not sure if it truly is ready for prime time, but it does exist.

**Comment by ZipCPU** [comment]
Thank you!  I'll take another look.
